### PR TITLE
Add Typescript

### PR DESCRIPTION
**Pull request by lcustodio**
I'm working on the code to run a dojo next week. I was wondering if the two stages completed so far make sense? Is this the right way to go?

### CODE REVIEW

**Comment by lcustodio** [comment]
Please do not consider to the other steps (they are still in Java as a placeholder).
Also, the PR still not ready to merge for this reason.

**Comment by bastiendavid** [comment]
Hi,

Stage 2 is OK.

Stage 1 is OK, you will just have to remove the `computePrice` method :)

Let me know if you need any help / advice on how to run the kata for a dojo.

**Comment by lcustodio** [comment]
Hey Bastien, thank you for the feedback. I removed the `computePrice` 🙃.

I ran one coding dojo with 5 people and it went quite well, their feedback was super positive. 
We just managed to get until the 2nd stage with one hour session. We are going to have another one tomorrow and see how it goes. 

I'll send you the feedback. So far what I can say is that the dojo is excellent. 🙌

**Comment by lcustodio** [comment]
I believe this PR is complete now, let me know if you expect something more.

**Pull request merged**
