### PR TITLE
Implement all stages in C++

### PR DESCRIPTION
**Pull request by misterk72**
Following the coding dojo from yesterday this an implementation in C++ of the speedrun-kata.
It uses CMake and googletest.

### CODE REVIEW

**Comment by bastiendavid** [comment]
Cool, thanks :)
I will need a little more time to review before merging, but 2 feedbacks:
- The test is not commented out in: `Stage1Test.cpp `
- You already started to remove the code duplication in `Stage5.cpp` by creating the method `countChars`. Do you think we can find a way of not doing this?

I will continue my review later.

It would be great if you could tell me what you think about these 2 feedback.

Let me know if you can make fixes - it's OK if you cannot, I will do the changes myself.

Thanks again :)

**Comment by misterk72** [comment]
Hello Bastien,
thank you very much for the feedbacks.
I will try to fix the two problems you saw ASAP.
For the second one I could inline and duplicate the code of the countChars() method inside the isEligible() method. What do you think about this?
Christophe

**Comment by bastiendavid** [comment]
Nice :)
Inlining was indeed a good option.
I will do a final review and merge it ASAP :)

**Comment by bastiendavid** [comment]
OK I merged, thanks!

One last question: I am not familiar with how C++ projects handle dependencies, but in the current version, you have to have the Google Test framework installed.
Could we improve this in a way that no setup would be required? This is just a suggestion for a future improvement. Right now I am OK with this version :)

**Comment by misterk72** [comment]
Thank you for accepting the pull request!
That's a good question and I see totally the interest of doing that.
Honestly I don't know if something like this exists in C++ but I will have
a look.

Thanks again,
Christophe

**Pull request merged**
