### PR TITLE
Feature/rust

### PR DESCRIPTION
**Pull request by Steranoid**
Implement all stages in rust

### CODE REVIEW

**Comment by bastiendavid** [comment]
Thanks, I will try to review and merge ASAP :)

**Comment by Steranoid** [comment]
> Thanks, I will try to review and merge ASAP :)

You just have to run the following command in the rust directory :
`cargo test`

Of course it will not compile since compute_price in stage 1 is not implemented, here is a simple solution if you want to test :
``` rust
fn compute_price(v: &std::vec::Vec<Items>) -> i32
{
  v.iter().map(Items::get_price).fold(0i32, std::ops::Add::add)
}
```

**Comment by bastiendavid** [comment]
Sounds great.

Commit https://github.com/bastiendavid/speedrun-kata/pull/4/commits/b4fd68fed7b87f2b845c5ea591bc3d6ab1156fab is actually implementing the Stage1
Do you think you can remove the implementation? ^^
If you cannot that's OK, I will do it :)

Also, just so you know, I made a silly typo in stage4, the discount is not correctly computed - it is added instead of being removed
I will fix it once the pull request has been merged.

**Comment by Steranoid** [comment]
Yes I didn't see I added it, I also corrected your typo.

**Comment by bastiendavid** [comment]
Merged, thanks :)

**Pull request merged**
